
# 代码高亮
highlight_theme: light

# 头图
index_img: 'https://api.btstu.cn/sjbz/api.php'
default_top_img: 'https://api.btstu.cn/sjbz/api.php'


# 背景丝带
canvas_fluttering_ribbon:
  enable: true
  mobile: false # 手机端

# 字体设置
font:
  global-font-size:
  code-font-size:
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Helvetica Neue", Lato, Roboto, "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif
  code-font-family: Menlo, "Fira Code", "PingFang SC", "Microsoft JhengHei", "Microsoft YaHei", sans-serif


cover:
  # 是否顯示文章封面
  index_enable: false
  aside_enable: false
  archives_enable: false
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
  default_cover: 

avatar:
  img: https://tse3-mm.cn.bing.net/th/id/OIP-C.su3IE2wUcfrRFVGX_K3iNgHaHa?pid=ImgDet&rs=1
  effect: false

translate:
  enable: true
  # 默認按鈕顯示文字(網站是簡體，應設置為'default: 繁')
  default: 繁
  #網站默認語言，1: 繁體中文, 2: 簡體中文
  defaultEncoding: 1
  #延遲時間,若不在前, 要設定延遲翻譯時間, 如100表示100ms,默認為0
  translateDelay: 0
  #當文字是簡體時，按鈕顯示的文字
  msgToTraditionalChinese: "繁"
  #當文字是繁體時，按鈕顯示的文字
  msgToSimplifiedChinese: "簡"
